/// Flutter icons NewsFeed
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NewsFeed
///      fonts:
///       - asset: fonts/NewsFeed.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class NewsFeedIcons {
  NewsFeedIcons._();

  static const _kFontFam = 'NewsFeed';

  static const IconData twitter = IconData(0xf099, fontFamily: _kFontFam);
  static const IconData facebook = IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData linkedin = IconData(0xf0e1, fontFamily: _kFontFam);
  static const IconData youtube_play = IconData(0xf16a, fontFamily: _kFontFam);
}
